@startuml

class MapsActivity {
  - mapApplication: MapApplicationService
  + {abstract} onCreate()
}

package application {
  class MapApplicationService {
    - map: Map
    - gps: GPS
    + startUp(): bool
  }
}

package domain {
    package model {
      class Map {
        - mMap: GoogleMap
        + {abstract} onMapReady()
      }

      class GPS {
        + enableCurrentLocation()
        - checkPermission()
      }
  }
}

MapsActivity *-- MapApplicationService
MapApplicationService o-- Map
MapApplicationService o-- GPS

@enduml