@startuml

MapsActivity -> MapApplicationService: 生成(MapsActivity)
MapsActivity -> MapCallback: 生成(MapApplicationService)
MapCallback --> MapsActivity: マップ表示時のコールバック返却

MapsActivity -> MapCallback: 表示完了&コールバック実行(GoogleMap)

activate MapCallback

MapCallback -> MapApplicationService: アプリケーション開始(GoogleMap)
MapApplicationService -> GPS: 生成(MapsActivity)
MapApplicationService -> GPS: 現在地取得(GoogleMap)
MapApplicationService -> MyMap: 生成(GoogleMap)
MyMap --> MapApplicationService: 返却

deactivate MapCallback

@enduml